### ISSUE TITLE
cannot import name 'args_control' from partially initialized module

### ISSUE THREAD

**Issue by VladUZH** [n0fate/chainbreaker#44]
### Discussed in https://github.com/n0fate/chainbreaker/discussions/43

<div type='discussions-op-text'>

<sup>Originally posted by **VladUZH** April 23, 2024</sup>
Hi. Getting this error when trying to execute the code. I understand that it is connected to the circular import but don't know how to fix the problem. Any help would be appreciated.

(.conda) (base) vlpetrov@Vladimirs-MacBook-Pro chainbreaker-1 % python -m chainbreaker -pa login.keychain-db -o output
/Users/vlpetrov/Documents/Programming/chainbreaker-1/.conda/bin/python: Error while finding module specification for 'chainbreaker.__main__' (ImportError: cannot import name 'args_control' from partially initialized module 'chainbreaker' (most likely due to a circular import) (/Users/vlpetrov/Documents/Programming/chainbreaker-1/chainbreaker/__init__.py))</div>

**Comment by llllIIIllll** [comment]
$ python -m chainbreaker  --dump-keychain-password-hash  MyKeychain.keychain-db

2024-10-05 07:56:44,779 - INFO - Version - 3.0.3
2024-10-05 07:56:44,780 - INFO - Chainbreaker : https://github.com/n0fate/chainbreaker
2024-10-05 07:56:44,780 - INFO - Version: 3.0.3
2024-10-05 07:56:44,780 - INFO - Runtime Command: /home/kali/test/111/chainbreaker/chainbreaker/__main__.py --dump-keychain-password-hash MyKeychain.keychain-db
2024-10-05 07:56:44,780 - INFO - Keychain: MyKeychain.keychain-db
2024-10-05 07:56:44,780 - INFO - Keychain MD5: ae0b4ed2b0200422987f23d925ca782f
2024-10-05 07:56:44,780 - INFO - Keychain 256: 305f80117f0643875fa98b5937c9a22c30d0fbc9f3c891501e86b86a2a470396
2024-10-05 07:56:44,780 - INFO - Dump Start: 2024-10-05 07:56:44.780019
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/kali/test/111/chainbreaker/chainbreaker/__main__.py", line 3, in <module>
    chainbreaker.main()
  File "/home/kali/test/111/chainbreaker/chainbreaker/__init__.py", line 1199, in main
    keychain = Chainbreaker(args.keychain, unlock_password=args.password, unlock_key=args.key,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/test/111/chainbreaker/chainbreaker/__init__.py", line 109, in __init__
    self.filepath = filepath
    ^^^^^^^^^^^^^
  File "/home/kali/test/111/chainbreaker/chainbreaker/__init__.py", line 623, in filepath
    self._read_keychain_to_buffer()
  File "/home/kali/test/111/chainbreaker/chainbreaker/__init__.py", line 210, in _read_keychain_to_buffer
    self.table_count, self.table_enum = self._get_table_name_to_list(self.record_list, self.table_list)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/test/111/chainbreaker/chainbreaker/__init__.py", line 291, in _get_table_name_to_list
    table_metadata, generic_list = self._get_table(table_list[count])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/test/111/chainbreaker/chainbreaker/__init__.py", line 275, in _get_table
    record_offset = _RECORD_OFFSET(self.kc_buffer[record_offset_base
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/test/111/chainbreaker/chainbreaker/schema.py", line 482, in __init__
    self.Value = _INT.STRUCT.unpack(buffer)[0]
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
struct.error: unpack requires a buffer of 4 bytes
